# Generated by Django 5.2 on 2025-04-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together={('attendance', 'teacher')},
        ),
    ]
