# Generated by Django 5.2 on 2025-04-25 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_teacherattendance_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ed', models.DateField(auto_now_add=True)),
                ('updated_ed', models.DateField(auto_now=True)),
                ('sarlavha', models.CharField(max_length=200, verbose_name='vazifa sarlavhasi')),
                ('topshirish_muddati', models.DateTimeField(verbose_name='Topshirish sanasi')),
                ('holati', models.CharField(choices=[('faol', 'Faol'), ('muddati_utgan', 'Muddati o`tgan'), ('arxiv', 'Arxivlangan')], default='faol', max_length=15)),
                ('fayl', models.FileField(blank=True, null=True, upload_to='uy_vazifalari/', verbose_name='Vazifa fayli')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_home_groupstudent', to='app.groupstudent')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_home_teacher', to='app.teacher')),
            ],
            options={
                'verbose_name': 'Uy vazifasi',
                'verbose_name_plural': 'Uy vazifalari',
                'ordering': ['-created_ed'],
            },
        ),
        migrations.CreateModel(
            name='Topshiriq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ed', models.DateField(auto_now_add=True)),
                ('updated_ed', models.DateField(auto_now=True)),
                ('topshirilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('javob', models.TextField(verbose_name='Talaba javobi')),
                ('ilova', models.FileField(blank=True, null=True, upload_to='topshiriqlar/')),
                ('baho', models.IntegerField(choices=[(0, 'Baholanmagan'), (1, 'Qoniqarsiz'), (2, 'Qoniqarli'), (3, 'Yaxshi'), (4, 'A`lo'), (5, 'Mukammal')], default=0, verbose_name='Topshiriq bahosi')),
                ('sharh', models.TextField(blank=True, verbose_name="O'qituvchi sharhi")),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topshiriqlar', to='app.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student', verbose_name='Topshiruvchi talaba')),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriqlar',
                'unique_together': {('homework', 'student')},
            },
        ),
    ]
