# Generated by Django 5.2 on 2025-04-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='created',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated',
        ),
    ]
