# Generated by Django 5.2 on 2025-04-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstudent',
            name='created',
        ),
        migrations.RemoveField(
            model_name='groupstudent',
            name='updated',
        ),
    ]
