# Generated by Django 5.2 on 2025-05-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.PositiveIntegerField(default=2025, verbose_name='yil'),
        ),
    ]
